### ISSUE TITLE
What is the "review app"

### ISSUE THREAD

**Issue by danprime** [cds-snc/etait-ici#5]
How do we use it?
![image](https://user-images.githubusercontent.com/2610409/52743546-44652000-2fa8-11e9-9863-6d3c395d6033.png)

**Comment by maxneuvians** [comment]
It is a thing that you can see in your PR and click on.

![screen shot 2019-02-13 at 4 00 31 pm](https://user-images.githubusercontent.com/867334/52743684-960daa80-2fa8-11e9-915c-4ee1da994462.png)

**Comment by maxneuvians** [comment]
I will add more context to the Readme! Good suggestion!

**Comment by maxneuvians** [comment]
Updated!
